---
namespace: jheddings
name: macos
version: 1.0.0
readme: README.md
description: A collection of utilities for working with macos.

# The URL of the originating SCM repository
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker

authors:
  - jheddings <jheddings@gmail.com>

license_file: LICENSE

tags:
  - tools

dependencies: {}

build_ignore:
  - poetry.lock
  - pyproject.yaml
  - Makefile
