---
namespace: jheddings
name: macos
version: "1.0.0"
readme: README.md
description: A collection of utilities for working with macos.

repository: https://github.com/jheddings/ansible-macos
issues: https://github.com/jheddings/ansible-macos/issues

authors:
  - jheddings <jheddings@gmail.com>

license_file: LICENSE

tags:
  - tools

dependencies: {}

build_ignore:
  - poetry.lock
  - pyproject.yaml
  - Makefile
